<a href="https://colab.research.google.com/github/ashrafhussain17/crime-analysis/blob/main/model_load.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving mymodel (1).h5 to mymodel (1).h5


In [ ]:
model = keras.models.load_model('mymodel (1).h5')

In [ ]:
model

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
def run_PCA(dataset, numberOfComponents):
    df = dataset
    number_of_columns = len(df.columns)
    x = df.iloc[:, 0:number_of_columns - 1].values
    y = df.iloc[:, number_of_columns - 1].values
    x = StandardScaler().fit_transform(x)
    pca = PCA(n_components=numberOfComponents)
    principalComponents = pca.fit_transform(x)
    principalDf = pd.DataFrame(principalComponents)
    print(type(principalDf))
    l = list(i for i in range(numberOfComponents + 1))
    print(l)
    # finalDf = pd.concat([principalDf, pd.DataFrame(y)])
    finalDf = principalDf.assign(yy=y)
    finalDf.columns = l
    return finalDf

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving readydata.csv to readydata.csv


In [ ]:
dataset = pd.read_csv('readydata.csv')

In [ ]:
dataset

iyear  imonth  iday  country  ...  property  ishostkid  ransom  success
0        1970       1     0       78  ...         1          0       0        1
1        1970       1     1      217  ...         1          0       0        1
2        1970       1     2      218  ...         0          0       0        0
3        1970       1     2      217  ...         1          0       0        1
4        1970       1     2      217  ...         1          0       0        1
...       ...     ...   ...      ...  ...       ...        ...     ...      ...
155430   2018      12    31      113  ...         1          0       0        1
155431   2018      12    31       41  ...        -9          0       0        1
155432   2018      12    31        4  ...         0          0       0        1
155433   2018      12    31        4  ...         1          0       0        1
155434   2018      12    31      603  ...         1          0       0        1

[155435 rows x 29 columns]

In [ ]:
dataset = run_PCA(dataset, 6)

<class 'pandas.core.frame.DataFrame'>
[0, 1, 2, 3, 4, 5, 6]


In [ ]:
dataset

0         1         2         3         4         5  6
0      -0.144536 -0.696205 -1.143974 -1.280059  0.176445 -0.692133  1
1      -2.036234 -3.223645 -0.638873 -1.665925  0.479919 -0.354831  1
2      -2.146963 -4.180155 -0.012105 -0.960747  0.435048  0.052397  0
3       3.042992 -3.495695 -1.464520 -2.075544  0.742871 -0.805305  1
4      -0.378178 -0.779499 -4.818792 -2.321352  0.607180 -0.067639  1
...          ...       ...       ...       ...       ...       ... ..
155430  3.499632  0.037161  0.556114  0.161179 -0.565165  1.059568  1
155431  1.343250  0.116611  2.155217  1.738469 -0.400229 -0.487863  1
155432 -1.699982  0.191199  0.598891  1.940905 -0.613726 -0.135456  1
155433 -0.107045  2.442107 -3.408358  1.577265 -0.323999  0.590527  1
155434  2.802406  2.586789 -2.849962 -4.431655 -0.036546  0.399647  1

[155435 rows x 7 columns]

In [ ]:
X = dataset.iloc[:, 0:6].values
y = dataset.iloc[:, 6].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [ ]:
X_train

array([[-1.48497807,  0.75040801, -0.74665268,  1.05044382, -0.52205266,
        -0.73084625],
       [-1.55193775,  0.74955121,  0.11682577, -0.20979312, -0.17372777,
        -0.72655896],
       [ 0.08072992, -0.5722267 , -4.49601663, -1.92695588,  0.45005535,
         0.45621255],
       ...,
       [-0.33515516,  2.27869103, -3.50336475,  0.79365558, -0.4172677 ,
         0.22888429],
       [-0.47739823,  1.3119091 , -0.29325802, -1.18187159, -0.22684998,
         0.74525602],
       [-1.90180258, -1.58434828, -2.50040902,  0.86032863,  0.18988293,
        -0.48145197]])

In [ ]:
y_train

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
model.summary

<bound method Model.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f817c841fd0>>

In [ ]:
y_train = y_train.reshape(-1,1)

In [ ]:
y_train

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [ ]:
result = model.fit(X_train, y_train, batch_size = 10, epochs = 10)

Epoch 1/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2952 - accuracy: 0.9062
Epoch 2/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2952 - accuracy: 0.9062
Epoch 3/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2951 - accuracy: 0.9062
Epoch 4/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2951 - accuracy: 0.9062
Epoch 5/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2950 - accuracy: 0.9062
Epoch 6/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2949 - accuracy: 0.9062
Epoch 7/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2949 - accuracy: 0.9062
Epoch 8/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2948 - accuracy: 0.9062
Epoch 9/10
13990/13990 [==============================] - 16s 1ms/step - loss: 0.2947 - accuracy: 0.9062
Epoch 10/10
13990/13990 [==============================

In [ ]:
for i in range(0,10):
  print(str(i) + ' th ' + str(result.history['accuracy'][i]))

0 th 0.9062126874923706
1 th 0.9062126874923706
2 th 0.9062126874923706
3 th 0.9062126874923706
4 th 0.9062126874923706
5 th 0.9062126874923706
6 th 0.9062126874923706
7 th 0.9062126874923706
8 th 0.9062126874923706
9 th 0.9062126874923706
